#!/usr/bin/env python

import sqlite3
import os.path
import uuid


def main():
    db_connection = connect_to_db("hookster.db")
    cursor = db_connection.cursor()

    for i in range(3):
        cursor.execute(
            f"""INSERT INTO Events VALUES('{generate_uuid()}', '{i}', '{i}')"""
        )

    db_connection.commit()
    db_connection.close()


def connect_to_db(database_file):
    """Connect to (or create) our sqlite3 database at the given filepath."""

    new_dbfile = not os.path.exists(database_file)
    connection = sqlite3.connect(database_file)

    if new_dbfile:
        # Populate the database with tables.
        cursor = connection.cursor()
        cursor.execute(
            """
            CREATE TABLE Events (
                id TEXT,
                name TEXT,
                description TEXT,
                PRIMARY KEY (id)
            )
            """
        )
        cursor.execute(
            """
            CREATE TABLE Dependencies (
                prerequisite TEXT,
                event TEXT,
                FOREIGN KEY(prerequisite) REFERENCES Events(id)
                FOREIGN KEY(event) REFERENCES Events(id)
            )
            """
        )

    return connection


def generate_uuid():
    return str(uuid.uuid1())


if __name__ == "__main__":
    main()


# vim: ft=python
